---
title: "Potato map test"
author: "Hannah Tarlyn"
date: "12/29/2020"
output: html_document
---

```{r setup, include=FALSE}
## Install and load packages for mapping
library("rnaturalearth")
library("rnaturalearthdata")
library("ggplot2")
library("rworldmap")
library(dplyr)
library(geosphere)
library(gpclib)
library(tidyverse)
library(mapdata)
library(raster)
library(geojsonio)
library(usmap)
```

## PNW mapping
### Obtain data, US states and Canadian provinces in and around PNW
```{r}
us <- getData("GADM",country="USA",level=1)
canada <- getData("GADM",country="CAN",level=1)
states <- c('Idaho', 'Oregon', 'Washington', 'Montana', 'California', 'Nevada', 'Utah', 'Wyoming')
provinces <- c("British Columbia", "Alberta")
```
### Subset data into US states and Canadian provinces
```{r}
us.states <- us[us$NAME_1 %in% states,]
ca.provinces  <- canada[canada$NAME_1 %in% provinces,]
```

## WA county map
```{r}
### Base WA county map
states <- map_data("state")
dim(states)
wa_df <- subset(states, region == "washington")
head(wa_df)

counties <- map_data("county")
wa_county <- subset(counties, region == "washington")
head(wa_county)

wa_base <- ggplot(data = wa_df,
                  mapping = aes(x = long,
                                y = lat,
                                group = 
group,
fill = subregion)) +
coord_fixed(1.3) +
geom_polygon(color = "black", fill = "gray")

wa_base + theme_classic() +
geom_polygon(data = wa_county, fill = NA, color = "white") +
geom_polygon(color = "black", fill = NA)  # get the state border back on top


###Add surrounding states and provinces to WA map
us <- getData("GADM",country="USA",level=1)
canada <- getData("GADM",country="CAN",level=1)
states <- c('Idaho', 'Oregon', 'California', 'Utah', 'Montana', 'Nevada', 'Wyoming')
provinces <- c("British Columbia", "Alberta")
### PNW
us.states <- us[us$NAME_1 %in% states,]
### Canada
ca.provinces <- canada[canada$NAME_1 %in% provinces,]


## Reading in potato acreage data from NASS from 1965-2015 and selecting year, county and value (acreage)
ShortHistoricAcreageCSV <- read.csv(file = 'HistoricPotatoData.csv')

ShortHistoricAcreage <- dplyr::select(ShortHistoricAcreageCSV, "County", "Year", "Value") 
## Delete rows that are for combined counties- fornot, cannot map multiple counties together, we will be mapping individual counties
ShortHistoricAcreage <- ShortHistoricAcreage[!grepl("COMBINED",ShortHistoricAcreage$County),]

##Coerce Value column from character to numeric
ShortHistoricAcreage$Value = as.numeric(gsub(",", "", ShortHistoricAcreage$Value))
ShortHistoricAcreage$Value
summary(as.numeric(ShortHistoricAcreage$Value))
lapply(ShortHistoricAcreage, unique)

##Rename county column in ShortHistoricAcreage to "subregion" to match the map county column name and change the ShortHistoricAcreage counties to all lowercase to match the map dataframe so they can be joined
colnames(ShortHistoricAcreage)[1] <- "subregion"

ShortHistoricAcreage$subregion <- tolower(ShortHistoricAcreage$subregion) 

## Fill in 0 as a placement for years when counties did not report any acreage. In some cases, counties only reported acreage for some years, but to properly map, the counties need to have an entry for each year or else they will not be included on the map when they did not report and no county boundaries will map on these years
ShortHistoricAcreageFilled <- ShortHistoricAcreage %>%
    complete(subregion, Year = 1965:2014, 
             fill = list(Value = 0)) 
## Read in csv of counties that were not included in the original NASS dataset: Asotin, Chelan, Clallam, Columbia, Ferry, Garfield, Jefferson, Mason, Pacific, Pend Oreille, San Juan, Skamania, Wahkiakum. This is done so the county borders of these counties will properly map. 
NAWACounties <- read.csv(file = 'NA_wa_counties.csv')

##Use rbind to add the NAWACounties df to the ShortHistoricAcreageFilled df
FullHistoricAcreage <- rbind(ShortHistoricAcreageFilled, NAWACounties)

##Joined county data, wa_county dataframe is map data for the counties in Washington state, FullHistoricAcreage includes the  potato acreage for each county over time
JoinedCounties <- inner_join(wa_county, FullHistoricAcreage, by = "subregion")

##Subset data into a few sections of year data- this makes processing the iterative maps easier/faster in terms of processing power needed by the computer
SubsetYears1965to1969 <- subset(JoinedCounties, Year<1970)
SubsetYears1970to1979 <- subset(JoinedCounties, Year>1969 & Year<1980)
SubsetYears1980to1989 <- subset(JoinedCounties, Year>1979 & Year<1990)
SubsetYears1990to1999 <- subset(JoinedCounties, Year>1989 & Year<2000)
SubsetYears2000to2014 <- subset(JoinedCounties, Year>1999)
```

```{r}
##Iterative year county maps: First take the code for the states and provinces surrounding WA (lines 118-123). Then add code for the WA county map using the first section of subset years (lines 124-139). Use facet_wrap (line 129) to create a map based on each year of data.

#Maps for 1965-1969
ggplot(us.states,
       aes(x=long, y=lat, group=group))+
  geom_path(size=0.25)+
  geom_path(data=ca.provinces, size=0.25,color="grey60")+
  geom_polygon(data=subset(us.states, NAME_1 %in% c('Idaho', 'Oregon', 'California', 'Utah', 'Montana', 'Nevada', 'Wyoming' )),
               aes(x=long, y=lat, group=group), fill="white", colour = "grey50", size=0.50)+ 
 geom_polygon(data=SubsetYears1965to1969,
               aes(x=long, y=lat, group=group,
               fill=Value), ###Fill color based on acreage value
                color="black", lwd=0.3, alpha=0.8) +
  scale_fill_gradient(low="blue", high="red") +
  facet_wrap(~ Year)+ ###Create a map based on each year
  theme_classic() + coord_map("conic", lat0 = 30) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(fill = "Acreage")+
  labs(caption = "Counties shown in grey were not included in the NASS data set.") +
  theme(plot.caption = element_text(hjust = 0.5))+ 
  theme(panel.background = element_rect(fill = "white", colour = "grey50"))+
 coord_map("bonne", lat0 = 50,
            xlim = c(-125, -114),ylim = c(42, 50))+
  xlab("Longitude") +
  ylab("Latitude")
  
  #Maps for 1970-1979
ggplot(us.states,
       aes(x=long, y=lat, group=group))+
  geom_path(size=0.25)+
  geom_path(data=ca.provinces, size=0.25,color="grey60")+
  geom_polygon(data=subset(us.states, NAME_1 %in% c('Idaho', 'Oregon', 'California', 'Utah', 'Montana', 'Nevada', 'Wyoming', 'Washington' )),
               aes(x=long, y=lat, group=group), fill="white", colour = "grey50", size=0.50)+ 
 geom_polygon(data=SubsetYears1970to1979,
               aes(x=long, y=lat, group=group,
               fill=Value), ###Fill color based on acreage value
                color="black", lwd=0.3, alpha=0.8) +
  scale_fill_gradient(low="blue", high="red") +
  facet_wrap(~ Year)+ ###Create a map based on each year
  theme_classic() + coord_map("conic", lat0 = 30) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(fill = "Acreage")+
  labs(caption = "Counties shown in grey were not included in the NASS data set.") +
  theme(plot.caption = element_text(hjust = 0.5))+ 
  theme(panel.background = element_rect(fill = "white", colour = "grey50"))+
 coord_map("bonne", lat0 = 50,
            xlim = c(-125, -114),ylim = c(42, 50))+
  xlab("Longitude") +
  ylab("Latitude")

#Maps for 1980-1989
ggplot(us.states,
       aes(x=long, y=lat, group=group))+
  geom_path(size=0.25)+
  geom_path(data=ca.provinces, size=0.25,color="grey60")+
  geom_polygon(data=subset(us.states, NAME_1 %in% c('Idaho', 'Oregon', 'California', 'Utah', 'Montana', 'Nevada', 'Wyoming', 'Washington' )),
               aes(x=long, y=lat, group=group), fill="white", colour = "grey50", size=0.50)+ 
 geom_polygon(data=SubsetYears1980to1989,
               aes(x=long, y=lat, group=group,
               fill=Value), ###Fill color based on acreage value
                color="black", lwd=0.3, alpha=0.8) +
  scale_fill_gradient(low="blue", high="red") +
  facet_wrap(~ Year)+ ###Create a map based on each year
  theme_classic() + coord_map("conic", lat0 = 30) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(fill = "Acreage")+
  labs(caption = "Counties shown in grey were not included in the NASS data set.") +
  theme(plot.caption = element_text(hjust = 0.5))+ 
  theme(panel.background = element_rect(fill = "white", colour = "grey50"))+
 coord_map("bonne", lat0 = 50,
            xlim = c(-125, -114),ylim = c(42, 50))+
  xlab("Longitude") +
  ylab("Latitude")

#Maps for 1990-1999
ggplot(us.states,
       aes(x=long, y=lat, group=group))+
  geom_path(size=0.25)+
  geom_path(data=ca.provinces, size=0.25,color="grey60")+
  geom_polygon(data=subset(us.states, NAME_1 %in% c('Idaho', 'Oregon', 'California', 'Utah', 'Montana', 'Nevada', 'Wyoming', 'Washington' )),
               aes(x=long, y=lat, group=group), fill="white", colour = "grey50", size=0.50)+ 
 geom_polygon(data=SubsetYears1990to1999,
               aes(x=long, y=lat, group=group,
               fill=Value), ###Fill color based on acreage value
                color="black", lwd=0.3, alpha=0.8) +
  scale_fill_gradient(low="blue", high="red") +
  facet_wrap(~ Year)+ ###Create a map based on each year
  theme_classic() + coord_map("conic", lat0 = 30) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(fill = "Acreage")+
  labs(caption = "Counties shown in grey were not included in the NASS data set.") +
  theme(plot.caption = element_text(hjust = 0.5))+ 
  theme(panel.background = element_rect(fill = "white", colour = "grey50"))+
 coord_map("bonne", lat0 = 50,
            xlim = c(-125, -114),ylim = c(42, 50))+
  xlab("Longitude") +
  ylab("Latitude")

#Maps for 2000-2014
ggplot(us.states,
       aes(x=long, y=lat, group=group))+
  geom_path(size=0.25)+
  geom_path(data=ca.provinces, size=0.25,color="grey60")+
  geom_polygon(data=subset(us.states, NAME_1 %in% c('Idaho', 'Oregon', 'California', 'Utah', 'Montana', 'Nevada', 'Wyoming', 'Washington' )),
               aes(x=long, y=lat, group=group), fill="white", colour = "grey50", size=0.50)+ 
 geom_polygon(data=SubsetYears2000to2014,
               aes(x=long, y=lat, group=group,
               fill=Value), ###Fill color based on acreage value
                color="black", lwd=0.3, alpha=0.8) +
  scale_fill_gradient(low="blue", high="red") +
  facet_wrap(~ Year)+ ###Create a map based on each year
  theme_classic() + coord_map("conic", lat0 = 30) + 
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(fill = "Acreage")+
  labs(caption = "Counties shown in grey were not included in the NASS data set.") +
  theme(plot.caption = element_text(hjust = 0.5))+ 
  theme(panel.background = element_rect(fill = "white", colour = "grey50"))+
 coord_map("bonne", lat0 = 50,
            xlim = c(-125, -114),ylim = c(42, 50))+
  xlab("Longitude") +
  ylab("Latitude")

```


